# Generated by Django 4.1.3 on 2022-12-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="total_likes",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
